package com.game.chiendh.iqtestforfun;

public class Utils {
	public static int getQuestion(int position) {
		switch (position+1) {
		case 1:
			return R.drawable.test1;
		case 2:
			return R.drawable.test2;
		case 3:
			return R.drawable.test3;
		case 4:
			return R.drawable.test4;
		case 5:
			return R.drawable.test5;
		case 6:
			return R.drawable.test6;
		case 7:
			return R.drawable.test7;
		case 8:
			return R.drawable.test8;
		case 9:
			return R.drawable.test9;
		case 10:
			return R.drawable.test10;
		case 11:
			return R.drawable.test11;
		case 12:
			return R.drawable.test12;
		case 13:
			return R.drawable.test13;
		case 14:
			return R.drawable.test14;
		case 15:
			return R.drawable.test15;
		case 16:
			return R.drawable.test16;
		case 17:
			return R.drawable.test17;
		case 18:
			return R.drawable.test18;
		case 19:
			return R.drawable.test19;
		case 20:
			return R.drawable.test20;
		case 21:
			return R.drawable.test21;
		case 22:
			return R.drawable.test22;
		case 23:
			return R.drawable.test23;
		case 24:
			return R.drawable.test24;
		case 25:
			return R.drawable.test25;
		case 26:
			return R.drawable.test26;
		case 27:
			return R.drawable.test27;
		case 28:
			return R.drawable.test28;
		case 29:
			return R.drawable.test29;
		case 30:
			return R.drawable.test30;
		case 31:
			return R.drawable.test31;
		case 32:
			return R.drawable.test32;
		case 33:
			return R.drawable.test33;
		case 34:
			return R.drawable.test34;
		case 35:
			return R.drawable.test35;
		case 36:
			return R.drawable.test36;
		case 37:
			return R.drawable.test37;
		case 38:
			return R.drawable.test38;
		case 39:
			return R.drawable.test39;
			
		default:
			break;
		}
		return -1;
	}
	
	public static int getAnswerA(int position){
		switch (position+1) {
		case 1:
			return R.drawable.a1;
		case 2:
			return R.drawable.a2;
		case 3:
			return R.drawable.a3;
		case 4:
			return R.drawable.a4;
		case 5:
			return R.drawable.a5;
		case 6:
			return R.drawable.a6;
		case 7:
			return R.drawable.a7;
		case 8:
			return R.drawable.a8;
		case 9:
			return R.drawable.a9;
		case 10:
			return R.drawable.a10;
		case 11:
			return R.drawable.a11;
		case 12:
			return R.drawable.a12;
		case 13:
			return R.drawable.a13;
		case 14:
			return R.drawable.a14;
		case 15:
			return R.drawable.a15;
		case 16:
			return R.drawable.a16;
		case 17:
			return R.drawable.a17;
		case 18:
			return R.drawable.a18;
		case 19:
			return R.drawable.a19;
		case 20:
			return R.drawable.a20;
		case 21:
			return R.drawable.a21;
		case 22:
			return R.drawable.a22;
		case 23:
			return R.drawable.a23;
		case 24:
			return R.drawable.a24;
		case 25:
			return R.drawable.a25;
		case 26:
			return R.drawable.a26;
		case 27:
			return R.drawable.a27;
		case 28:
			return R.drawable.a28;
		case 29:
			return R.drawable.a29;
		case 30:
			return R.drawable.a30;
		case 31:
			return R.drawable.a31;
		case 32:
			return R.drawable.a32;
		case 33:
			return R.drawable.a33;
		case 34:
			return R.drawable.a34;
		case 35:
			return R.drawable.a35;
		case 36:
			return R.drawable.a36;
		case 37:
			return R.drawable.a37;
		case 38:
			return R.drawable.a38;
		case 39:
			return R.drawable.a39;
			
		default:
			break;
		}
		return -1;
	}
	public static int getAnswerB(int position){
		switch (position+1) {
		case 1:
			return R.drawable.b1;
		case 2:
			return R.drawable.b2;
		case 3:
			return R.drawable.b3;
		case 4:
			return R.drawable.b4;
		case 5:
			return R.drawable.b5;
		case 6:
			return R.drawable.a6;
		case 7:
			return R.drawable.b7;
		case 8:
			return R.drawable.b8;
		case 9:
			return R.drawable.b9;
		case 10:
			return R.drawable.b10;
		case 11:
			return R.drawable.b11;
		case 12:
			return R.drawable.b12;
		case 13:
			return R.drawable.b13;
		case 14:
			return R.drawable.b14;
		case 15:
			return R.drawable.b15;
		case 16:
			return R.drawable.b16;
		case 17:
			return R.drawable.b17;
		case 18:
			return R.drawable.b18;
		case 19:
			return R.drawable.b19;
		case 20:
			return R.drawable.b20;
		case 21:
			return R.drawable.b21;
		case 22:
			return R.drawable.b22;
		case 23:
			return R.drawable.b23;
		case 24:
			return R.drawable.b24;
		case 25:
			return R.drawable.b25;
		case 26:
			return R.drawable.b26;
		case 27:
			return R.drawable.b27;
		case 28:
			return R.drawable.b28;
		case 29:
			return R.drawable.b29;
		case 30:
			return R.drawable.b30;
		case 31:
			return R.drawable.b31;
		case 32:
			return R.drawable.b32;
		case 33:
			return R.drawable.b33;
		case 34:
			return R.drawable.b34;
		case 35:
			return R.drawable.b35;
		case 36:
			return R.drawable.b36;
		case 37:
			return R.drawable.a37;
		case 38:
			return R.drawable.b38;
		case 39:
			return R.drawable.b39;
			
		default:
			break;
		}
		return -1;
	}

	public static int getAnswerC(int position){
		switch (position+1) {
		case 1:
			return R.drawable.c1;
		case 2:
			return R.drawable.c2;
		case 3:
			return R.drawable.c3;
		case 4:
			return R.drawable.c4;
		case 5:
			return R.drawable.c5;
		case 6:
			return R.drawable.c6;
		case 7:
			return R.drawable.c7;
		case 8:
			return R.drawable.c8;
		case 9:
			return R.drawable.c9;
		case 10:
			return R.drawable.c10;
		case 11:
			return R.drawable.c11;
		case 12:
			return R.drawable.c12;
		case 13:
			return R.drawable.c13;
		case 14:
			return R.drawable.c14;
		case 15:
			return R.drawable.c15;
		case 16:
			return R.drawable.c16;
		case 17:
			return R.drawable.c17;
		case 18:
			return R.drawable.c18;
		case 19:
			return R.drawable.c19;
		case 20:
			return R.drawable.c20;
		case 21:
			return R.drawable.c21;
		case 22:
			return R.drawable.c22;
		case 23:
			return R.drawable.c23;
		case 24:
			return R.drawable.c24;
		case 25:
			return R.drawable.c25;
		case 26:
			return R.drawable.c26;
		case 27:
			return R.drawable.c27;
		case 28:
			return R.drawable.c28;
		case 29:
			return R.drawable.c29;
		case 30:
			return R.drawable.c30;
		case 31:
			return R.drawable.c31;
		case 32:
			return R.drawable.c32;
		case 33:
			return R.drawable.c33;
		case 34:
			return R.drawable.c34;
		case 35:
			return R.drawable.c35;
		case 36:
			return R.drawable.c36;
		case 37:
			return R.drawable.c37;
		case 38:
			return R.drawable.c38;
		case 39:
			return R.drawable.c39;
			
		default:
			break;
		}
		return -1;
	}
	
	public static int getAnswerD(int position){
		switch (position+1) {
		case 1:
			return R.drawable.d1;
		case 2:
			return R.drawable.d2;
		case 3:
			return R.drawable.d3;
		case 4:
			return R.drawable.d4;
		case 5:
			return R.drawable.d5;
		case 6:
			return R.drawable.d6;
		case 7:
			return R.drawable.d7;
		case 8:
			return R.drawable.d8;
		case 9:
			return R.drawable.d9;
		case 10:
			return R.drawable.d10;
		case 11:
			return R.drawable.d11;
		case 12:
			return R.drawable.d12;
		case 13:
			return R.drawable.d13;
		case 14:
			return R.drawable.d14;
		case 15:
			return R.drawable.d15;
		case 16:
			return R.drawable.d16;
		case 17:
			return R.drawable.d17;
		case 18:
			return R.drawable.d18;
		case 19:
			return R.drawable.d19;
		case 20:
			return R.drawable.d20;
		case 21:
			return R.drawable.d21;
		case 22:
			return R.drawable.d22;
		case 23:
			return R.drawable.d23;
		case 24:
			return R.drawable.d24;
		case 25:
			return R.drawable.d25;
		case 26:
			return R.drawable.d26;
		case 27:
			return R.drawable.d27;
		case 28:
			return R.drawable.d28;
		case 29:
			return R.drawable.d29;
		case 30:
			return R.drawable.d30;
		case 31:
			return R.drawable.d31;
		case 32:
			return R.drawable.d32;
		case 33:
			return R.drawable.d33;
		case 34:
			return R.drawable.d34;
		case 35:
			return R.drawable.d35;
		case 36:
			return R.drawable.d36;
		case 37:
			return R.drawable.d37;
		case 38:
			return R.drawable.d38;
		case 39:
			return R.drawable.d39;
			
		default:
			break;
		}
		return -1;
	}
	
	public static int getAnswerE(int position){
		switch (position+1) {
		case 1:
			return R.drawable.e1;
		case 2:
			return R.drawable.e2;
		case 3:
			return R.drawable.e3;
		case 4:
			return R.drawable.e4;
		case 5:
			return R.drawable.e5;
		case 6:
			return R.drawable.e6;
		case 7:
			return R.drawable.e7;
		case 8:
			return R.drawable.e8;
		case 9:
			return R.drawable.e9;
		case 10:
			return R.drawable.e10;
		case 11:
			return R.drawable.e11;
		case 12:
			return R.drawable.e12;
		case 13:
			return R.drawable.e13;
		case 14:
			return R.drawable.e14;
		case 15:
			return R.drawable.e15;
		case 16:
			return R.drawable.e16;
		case 17:
			return R.drawable.e17;
		case 18:
			return R.drawable.e18;
		case 19:
			return R.drawable.e19;
		case 20:
			return R.drawable.e20;
		case 21:
			return R.drawable.e21;
		case 22:
			return R.drawable.e22;
		case 23:
			return R.drawable.e23;
		case 24:
			return R.drawable.e24;
		case 25:
			return R.drawable.e25;
		case 26:
			return R.drawable.e26;
		case 27:
			return R.drawable.e27;
		case 28:
			return R.drawable.e28;
		case 29:
			return R.drawable.e29;
		case 30:
			return R.drawable.e30;
		case 31:
			return R.drawable.e31;
		case 32:
			return R.drawable.e32;
		case 33:
			return R.drawable.e33;
		case 34:
			return R.drawable.e34;
		case 35:
			return R.drawable.e35;
		case 36:
			return R.drawable.e36;
		case 37:
			return R.drawable.e37;
		case 38:
			return R.drawable.e38;
		case 39:
			return R.drawable.e39;
			
		default:
			break;
		}
		return -1;
	}
	
	public static int getAnswerF(int position){
		switch (position+1) {
		case 1:
			return R.drawable.f1;
		case 2:
			return R.drawable.f2;
		case 3:
			return R.drawable.f3;
		case 4:
			return R.drawable.f4;
		case 5:
			return R.drawable.f5;
		case 6:
			return R.drawable.f6;
		case 7:
			return R.drawable.f7;
		case 8:
			return R.drawable.f8;
		case 9:
			return R.drawable.f9;
		case 10:
			return R.drawable.f10;
		case 11:
			return R.drawable.f11;
		case 12:
			return R.drawable.f12;
		case 13:
			return R.drawable.f13;
		case 14:
			return R.drawable.f14;
		case 15:
			return R.drawable.f15;
		case 16:
			return R.drawable.f16;
		case 17:
			return R.drawable.f17;
		case 18:
			return R.drawable.f18;
		case 19:
			return R.drawable.f19;
		case 20:
			return R.drawable.f20;
		case 21:
			return R.drawable.f21;
		case 22:
			return R.drawable.f22;
		case 23:
			return R.drawable.f23;
		case 24:
			return R.drawable.f24;
		case 25:
			return R.drawable.f25;
		case 26:
			return R.drawable.f26;
		case 27:
			return R.drawable.f27;
		case 28:
			return R.drawable.f28;
		case 29:
			return R.drawable.f29;
		case 30:
			return R.drawable.f30;
		case 31:
			return R.drawable.f31;
		case 32:
			return R.drawable.f32;
		case 33:
			return R.drawable.f33;
		case 34:
			return R.drawable.f34;
		case 35:
			return R.drawable.f35;
		case 36:
			return R.drawable.f36;
		case 37:
			return R.drawable.f37;
		case 38:
			return R.drawable.f38;
		case 39:
			return R.drawable.f39;
			
		default:
			break;
		}
		return -1;
	}

	public static int getAnswerG(int position){
		switch (position+1) {
		case 1:
			return R.drawable.g1;
		case 2:
			return R.drawable.g2;
		case 3:
			return R.drawable.g3;
		case 4:
			return R.drawable.g4;
		case 5:
			return R.drawable.g5;
		case 6:
			return R.drawable.g6;
		case 7:
			return R.drawable.g7;
		case 8:
			return R.drawable.g8;
		case 9:
			return R.drawable.g9;
		case 10:
			return R.drawable.g10;
		case 11:
			return R.drawable.g11;
		case 12:
			return R.drawable.g12;
		case 13:
			return R.drawable.g13;
		case 14:
			return R.drawable.g14;
		case 15:
			return R.drawable.g15;
		case 16:
			return R.drawable.g16;
		case 17:
			return R.drawable.g17;
		case 18:
			return R.drawable.g18;
		case 19:
			return R.drawable.g19;
		case 20:
			return R.drawable.g20;
		case 21:
			return R.drawable.g21;
		case 22:
			return R.drawable.g22;
		case 23:
			return R.drawable.g23;
		case 24:
			return R.drawable.g24;
		case 25:
			return R.drawable.g25;
		case 26:
			return R.drawable.g26;
		case 27:
			return R.drawable.g27;
		case 28:
			return R.drawable.g28;
		case 29:
			return R.drawable.g29;
		case 30:
			return R.drawable.g30;
		case 31:
			return R.drawable.g31;
		case 32:
			return R.drawable.g32;
		case 33:
			return R.drawable.g33;
		case 34:
			return R.drawable.g34;
		case 35:
			return R.drawable.g35;
		case 36:
			return R.drawable.g36;
		case 37:
			return R.drawable.g37;
		case 38:
			return R.drawable.g38;
		case 39:
			return R.drawable.g39;
			
		default:
			break;
		}
		return -1;
	}

	public static int getAnswerH(int position){
		switch (position+1) {
		case 1:
			return R.drawable.h1;
		case 2:
			return R.drawable.h2;
		case 3:
			return R.drawable.h3;
		case 4:
			return R.drawable.h4;
		case 5:
			return R.drawable.h5;
		case 6:
			return R.drawable.h6;
		case 7:
			return R.drawable.h7;
		case 8:
			return R.drawable.h8;
		case 9:
			return R.drawable.h9;
		case 10:
			return R.drawable.h10;
		case 11:
			return R.drawable.h11;
		case 12:
			return R.drawable.h12;
		case 13:
			return R.drawable.h13;
		case 14:
			return R.drawable.h14;
		case 15:
			return R.drawable.h15;
		case 16:
			return R.drawable.h16;
		case 17:
			return R.drawable.h17;
		case 18:
			return R.drawable.h18;
		case 19:
			return R.drawable.h19;
		case 20:
			return R.drawable.h20;
		case 21:
			return R.drawable.h21;
		case 22:
			return R.drawable.h22;
		case 23:
			return R.drawable.h23;
		case 24:
			return R.drawable.h24;
		case 25:
			return R.drawable.h25;
		case 26:
			return R.drawable.h26;
		case 27:
			return R.drawable.h27;
		case 28:
			return R.drawable.h28;
		case 29:
			return R.drawable.h29;
		case 30:
			return R.drawable.h30;
		case 31:
			return R.drawable.h31;
		case 32:
			return R.drawable.h32;
		case 33:
			return R.drawable.h33;
		case 34:
			return R.drawable.h34;
		case 35:
			return R.drawable.h35;
		case 36:
			return R.drawable.h36;
		case 37:
			return R.drawable.h37;
		case 38:
			return R.drawable.h38;
		case 39:
			return R.drawable.h39;
			
		default:
			break;
		}
		return -1;
	}

}
